### PR TITLE
fix #4: Add karma globally and fix test.sh

### LINKED ISSUE #4: Add karma globally and fix test.sh
```sh
if [[ ! -x ./node_modules/karma/bin/karma || ! -x ./node_modules/jshint/bin/jshint ]]; then
        npm install
fi
```

We want to avoid this install during ci. It would be good to grab the package.json from sirepo dynamically during the build of sirepo-ci and then do an npm install -g or whatever as vagrant (not root). Then test.sh should be fixed to look for jshint and karma dynamically with an npm command so that it doesn't assume it is a local install.

### PR DESCRIPTION
**Pull request by rorour**

### CODE REVIEW

File: container-conf/build.sh [hunk 1]
```diff
@@ -8,3 +8,15 @@ build_as_root() {
     build_yum config-manager --set-enabled google-chrome
     build_yum install google-chrome-stable
 }
+
+build_as_run_user() {
+    umask 022
+    cd ~
+    git clone https://github.com/radiasoft/sirepo.git
+    cd sirepo
+    declare -a d=($(jq -r '.devDependencies | keys |  @sh' package.json))
```
Comment (e-carlin) [inline container-conf/build.sh]: I know the example I showed you was using declare but inside of a function you can use `local -a ...`. From reading `man bash` it seems there is no practical difference between local and declare inside of a function used in this way but our style is to use local inside of functions.

File: container-conf/build.sh [hunk 2]
```diff
@@ -8,3 +8,15 @@ build_as_root() {
...
+    for n in "${d[@]}"
```
Comment (e-carlin) [inline container-conf/build.sh]: Our style of for loops is to do `for x in y; do`. So, move the `do` below up and put a `; ` before it.

File: container-conf/build.sh [hunk 3]
```diff
@@ -8,3 +8,15 @@ build_as_root() {
...
+    do
+      npm install -g $(eval n=$n && echo $n)
```
Comment (e-carlin) [inline container-conf/build.sh]: eval is generally a sign that you need to tread carefully and try to find a different way of doing things. For example, I don't know what the restrictions are on npm package names but maybe `; env` is a valid package name. If you do
```bash
n='\; env'
npm install -g $(eval n=$n && echo $n)
>>> 8.12.1
```
I was hoping that might print out our entire env which would be a security hole. But, instead it prints out 8.12.1 which I believe is the version of npm I have installed. Not terrible but not what we want the code to do. If I was more clever I imagine I could craft a package name that would do something worse.

So, we need to find a way to do this w/o eval. jq is a pain so that isn't easy. I tried a few different things but I think this might be the best option:

```bash
    local -a d=($(jq -r '.devDependencies | keys[] |  @sh' package.json))
    npm install -g "${d[@]}"
```

@robnagler can you add your thoughts? I'm worried there may be some word splitting / expansion problems but I'm hopeful with the quotes it gets around them...

One final issue is that the correct versions aren't installed. The package.json specifies version of the packages (currently all "latest" but it hasn't always been that way). So, we need to install the correct version of each package too (ex `npm install -g karma@latest`). I imagine jq has a way to get the values as well as the keys. So, you could get the two lists and either zip them together somehow (not sure if bash has a feature for this) or iterate with and index and index into both lists. Happy to brainstorm how to do it.

File: container-conf/build.sh (hunk 1 above)
Comment (robnagler) [reply container-conf/build.sh]: Yes, we standardize on `local`. We also put some space:

```bash
    local -a d=( $(jq -r '.devDependencies | keys |  @sh' package.json) )
```

Comment (robnagler) [reply container-conf/build.sh]: I think we know something about the data in this case so we can do something simpler:

```sh
npm install -g $(jq -M -r '.devDependencies | keys | @tsv' package.json)
```

If you really don't want to trust the data, then something like this is the way @sh was intended:

```sh
eval npm install -g $(jq -M -r '.devDependencies | keys | @sh' package.json)
```

**Review by robnagler — CHANGES_REQUESTED** [review]

File: container-conf/build.sh (hunk 1 above)
Comment (rorour) [reply container-conf/build.sh]: 2d4228bcd57cb82b5057fc1195e1f5edc29f0efa

File: container-conf/build.sh (hunk 2 above)
Comment (rorour) [reply container-conf/build.sh]: 2d4228bcd57cb82b5057fc1195e1f5edc29f0efa

**Comment by robnagler** [comment]
Ready for another review @rorour?

**Comment by rorour** [comment]
@robnagler Not yet, Evan pointed out that I need to add the version as well- trying to figure that out

File: container-conf/build.sh (hunk 3 above)
Comment (rorour) [reply container-conf/build.sh]: https://github.com/radiasoft/container-sirepo-ci/pull/6/commits/ee4dd7311150d33a05b20722d36134b58d2bb875

File: container-conf/build.sh [hunk 4]
```diff
@@ -8,3 +8,13 @@ build_as_root() {
     build_yum config-manager --set-enabled google-chrome
     build_yum install google-chrome-stable
 }
+
+build_as_run_user() {
+    umask 022
```
Comment (robnagler) [inline container-conf/build.sh]: unnecessary, [done here](https://github.com/radiasoft/containers/blob/a86906589709cabbe6bfffb62497820dfb94ac7d/bin/build.sh#L231).

File: container-conf/build.sh [hunk 5]
```diff
@@ -8,3 +8,13 @@ build_as_root() {
...
+    cd ~
```
Comment (robnagler) [inline container-conf/build.sh]: `cd ~` is same as `cd`. However, neither should be done. Downloads should happen in the [build_dir](https://github.com/radiasoft/containers/blob/a86906589709cabbe6bfffb62497820dfb94ac7d/bin/build.sh#L299) which is the current directory when the build is run.

File: container-conf/build.sh [hunk 6]
```diff
@@ -8,3 +8,13 @@ build_as_root() {
...
+    git clone https://github.com/radiasoft/sirepo.git
```
Comment (robnagler) [inline container-conf/build.sh]: This is a reasonable way to do this, but it would be more efficient to: 

```sh
install_url radiasoft/sirepo
install_download package.json > package.json
```

install_url [knows about github.com](https://github.com/radiasoft/download/blob/84922815033e849b0f017102cb4e30572d98bd67/bin/install.sh#L391), which is the default install_server, and then it will download just the contents of package.json which is very small in comparison to the whole sirepo repo. 

install_download has [further hacks](https://github.com/radiasoft/download/blob/84922815033e849b0f017102cb4e30572d98bd67/bin/install.sh#L83) to know how to download efficiently from github.com, which is a bit quirky.

File: container-conf/build.sh [hunk 7]
```diff
@@ -8,3 +8,13 @@ build_as_root() {
...
+    cd sirepo
+    local -a d=( $(jq -M -r '.devDependencies | keys | map(. + "@") | @tsv' package.json) )
+    local -a v=( $(jq -M -r '[.devDependencies[]] | @tsv' package.json) )
+    npm install -g $(for i in "${!d[@]}"; do printf " %s%s" "${d[$i]}" "${v[$i]}"; done)
```
Comment (robnagler) [inline container-conf/build.sh]: This is very clever, but it is is also one line. In this case, make it a function `sirepo_ci_parse_dependencies` which gets called:

```sh
npm install -g $(sirepo_ci_parse_dependencies)
```

This relies on the fact that individual package names don't have spaces or special chars, which is relatively safe since we are parsing a file file from one of our own repos, but would be good to document this.

I think the jq should be simplified to remove the `| map(. + "@")`, and also clean up the printf a bit:

```sh
printf '%s@%s\n' "${d[$i]}" "${v[$i]}"
```

Do not use double quotes unless interpolation is required, which it isn't for the format string. The double quotes are necessary for the d and v args.

And, after seeing `map` in your code (new to me!), I was curious is it possible to do this on one line with jq. ([Here is a clue](https://stackoverflow.com/a/25378171)). If you write sirepo_ci_parse_dependencies as a function, you can replace it with our one line jq, which could then also be piped to jq, e.g.

```sh
install_url radiasoft/sirepo
npm -g $(install_download packages.json | sirepo_ci_parse_dependencies)
```

I'm going to leave this one as an exercise to the reader.

File: container-conf/build.sh [hunk 8]
```diff
@@ -8,3 +8,13 @@ build_as_root() {
     build_yum config-manager --set-enabled google-chrome
     build_yum install google-chrome-stable
 }
+
+build_as_run_user() {
+    umask 022
+    cd ~
+    git clone https://github.com/radiasoft/sirepo.git
+    cd sirepo
+    local -a d=( $(jq -M -r '.devDependencies | keys | map(. + "@") | @tsv' package.json) )
```
Comment (robnagler) [inline container-conf/build.sh]: I don't think you need the -M when the output is specified (`@tsv`).

**Review by robnagler — CHANGES_REQUESTED** [review]

File: container-conf/build.sh (hunk 6 above)
Comment (e-carlin) [reply container-conf/build.sh]: One thought on the global install, if a PR has a different version specified (or adds/removes deps) then this won't pick it up. Is that a problem worth solving?

Comment (robnagler) [reply container-conf/build.sh]: This is a very narrow set of deps. The bigger problem is beamsim, on which this image is based. We will still manage that process separately. We release pretty rapidly so we don't need to worry about PRs that have dependency conflicts. The PR check will fail, and then we'll rebuild beamsim and sirepo-ci. Our goal is to make our software backwards/forwards compatible so the latest beamsim can run relatively recent sirepo code.

File: container-conf/build.sh (hunk 8 above)
Comment (rorour) [reply container-conf/build.sh]: 91034b60c74e645b2b6c07a317c7888a4fa06831

File: container-conf/build.sh (hunk 7 above)
Comment (rorour) [reply container-conf/build.sh]: 91034b60c74e645b2b6c07a317c7888a4fa06831

File: container-conf/build.sh (hunk 6 above)
Comment (rorour) [reply container-conf/build.sh]: 91034b60c74e645b2b6c07a317c7888a4fa06831

File: container-conf/build.sh (hunk 4 above)
Comment (rorour) [reply container-conf/build.sh]: 91034b60c74e645b2b6c07a317c7888a4fa06831

File: container-conf/build.sh (hunk 5 above)
Comment (rorour) [reply container-conf/build.sh]: 91034b60c74e645b2b6c07a317c7888a4fa06831

**Review by robnagler — APPROVED** [review]
